version: "3.9"

services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  etl:
    build: ./etl
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env


  app:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./data-brute:/app/data-brute
    env_file:
      - .env


  watchdog:
    build: ./watchdog
    volumes:
      - ./data-brute:/app/data-brute
      - ./resultat_extraction:/app/resultat_extraction
      - ./watchdog/log:/app/log
    depends_on:
      - db
    env_file:
      - .env



volumes:
  pgdata:
